name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - id: create_release
      name: Create Release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  build:
    needs: create_release
    strategy:
      matrix:
        platform: [
          'linux-arm',
          'linux-arm64',
          'linux-x64',
          'darwin-x64',
        ]

        include:
          - platform: 'linux-arm'
            host-os: 'ubuntu-latest'
          - platform: 'linux-arm64'
            host-os: 'ubuntu-latest'
          - platform: 'linux-x64'
            host-os: 'ubuntu-latest'
          - platform: 'darwin-x64'
            host-os: 'macos-latest'

    runs-on: ${{ matrix.host-os }}

    env:
      UPLOAD_URL: ${{ needs.create_release.outputs.upload_url }}
      FOO: ${GITHUB_REF:10}
      FOOO: ${{GITHUB_REF:10}}

    steps:
    - run: printenv
    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
    - uses: actions/checkout@v1
    - name: Build adapter
      run: |
        ./build.sh "${{ matrix.platform }}"
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: lumencache-adapter-${{ env.RELEASE_VERSION }}-${{ matrix.platform }}.tgz
        asset_name: lumencache-adapter-${{ env.RELEASE_VERSION }}-${{ matrix.platform }}.tgz
        asset_content_type: application/zip
    - name: Upload Release Asset Checksum
      id: upload-release-asset-checksum
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: lumencache-adapter-${{ env.RELEASE_VERSION }}-${{ matrix.platform }}.tgz.sha256sum
        asset_name: lumencache-adapter-${{ env.RELEASE_VERSION }}-${{ matrix.platform }}.tgz.sha256sum
        asset_content_type: text/plain
